POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBldGVybiIsImlkIjoiNjQyYTlhNzk4ZjAwN2U3MWFmNDI3YTNiIiwiaWF0IjoxNjgxOTE0MTA2LCJleHAiOjE2ODE5MTc3MDZ9.oAVguzf3xooi3BB60QaR6Yr8Dmk-RrVn66TYIdu3b_I

{
    "content": "abanananana",
    "important": true
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "important": true
}